defaults:
  - _self_
  - model: vl4str
  - charset: digits_only
  - dataset: real

# Fix abs_root path to use forward slashes for consistency
abs_root: C:/Users/jared/PycharmProjects/Jersey-Number-Recognition

model:
  # No changes needed here as charset is overridden
  charset_test: "0123456789"  # Change to digits only
  warmup_pct: 0.1  # Use 10% of the validation steps for warmup


data:
  # Fix paths to use forward slashes
  root_dir: ${abs_root}/data/SoccerNet/jersey-2023/extracted
  train_dir: train/images

  # Make sure labels file is referenced
  train_label_path: ${abs_root}/data/SoccerNet/jersey-2023/extracted/train/train_gt.json
  val_label_path: ${abs_root}/data/SoccerNet/jersey-2023/extracted/val/val_gt.json

trainer:
  # Reduce training epochs for faster results
  max_epochs: 5
  gpus: 1  # Assuming you have one GPU